language: rust
os:
  - linux
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
# deploy:
#   provider: cargo
#   on:
#     tags: true
#     branch: master
