[package]
name = "external-ip"
version = "0.1.0"
authors = ["Dario Meloni <mellon85@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mellon85/external-ip"
description = """
Asynchronous library to retrieve the system external IP
"""

[dependencies]
futures = "^0.3"
reqwest = "^0.10"
log = "^0.4"
c-ares-resolver = "^7"

[dev-dependencies]
tokio-test = "^0.2"
mockall = "^0.6"


[patch.crates-io]
reqwest = {git="https://github.com/seanmonstar/reqwest", branch="release-0.10.0"}
