[package]
name = "external-ip"
version = "0.1.0"
authors = ["Dario Meloni <mellon85@gmail.com>"]
edition = "2018"

[dependencies]
futures = "^0.3"
reqwest = "^0.10"
log = "^0.4"

[dev-dependencies]
tokio-test = "*"
mockall = "*"


[patch.crates-io]
reqwest = {git="https://github.com/seanmonstar/reqwest", branch="release-0.10.0"}
